camera:
  generic_camera_node:
    ros__parameters:
      camera_calibration_file: file:///workspaces/via-sdk/src/drivers/via_camera_nodes/config/camera.yaml
      file_name: "0"
      frame_id: camera
      image_height: 720
      image_width: 1280
      use_sim_time: false